/* SPDX-License-Identifier: GPL-2.0-or-later */
#ifndef MSI_PSU_H
#define MSI_PSU_H

#define USB_VID_MSI 0x0DB0

enum msi_psu_usb_pid {
	USB_PID_MEG_AI1000P = 0xE749,
	USB_PID_MEG_AI1300P = 0x56D4,
};

/* Unused in MSI Control Center but for future reference */
enum msi_psu_alert_status {
	MSI_PSU_ALERT_STATUS_OVP_12V = 0,
	MSI_PSU_ALERT_STATUS_OVP_5V,
	MSI_PSU_ALERT_STATUS_OVP_3_3V,
	MSI_PSU_ALERT_STATUS_UVP_12V,
	MSI_PSU_ALERT_STATUS_UVP_5V,
	MSI_PSU_ALERT_STATUS_UVP_3_3V,
	MSI_PSU_ALERT_STATUS_OCP_12V,
	MSI_PSU_ALERT_STATUS_OCP_5V,
	MSI_PSU_ALERT_STATUS_OCP_3_3V,
	MSI_PSU_ALERT_STATUS_OCP_12V1,
	MSI_PSU_ALERT_STATUS_OCP_12V2,
	MSI_PSU_ALERT_STATUS_OCP_12V3,
	MSI_PSU_ALERT_STATUS_OCP_12V4,
	MSI_PSU_ALERT_STATUS_OPP,
	MSI_PSU_ALERT_STATUS_OTP,
	MSI_PSU_ALERT_STATUS_FAN,
	MSI_PSU_ALERT_STATUS_AC,
};

/* HID command byte */
enum msi_psu_cmd {
	MSI_PSU_CMD_MFR_ID = 0x10,
	MSI_PSU_CMD_MFR_MODEL = 0x11,
	MSI_PSU_CMD_MFR_REVISION = 0x12,
	MSI_PSU_CMD_MFR_SERIAL = 0x13,
	MSI_PSU_CMD_VIN = 0x20,
	MSI_PSU_CMD_VOUT_12V5 = 0x22, /* 12V5 is for multi-rail (5 rails) */
	MSI_PSU_CMD_IOUT_12V5 = 0x23,
	MSI_PSU_CMD_VOUT_12 = 0x24,
	MSI_PSU_CMD_IOUT_12 = 0x25,
	MSI_PSU_CMD_VOUT_5 = 0x26,
	MSI_PSU_CMD_IOUT_5 = 0x27,
	MSI_PSU_CMD_VOUT_3_3 = 0x28,
	MSI_PSU_CMD_IOUT_3_3 = 0x29,
	MSI_PSU_CMD_POUT = 0x2A,
	MSI_PSU_CMD_EFFICIENCY = 0x2B,
	MSI_PSU_CMD_TEMPERATURE = 0x30,
	MSI_PSU_CMD_FAN_SPEED = 0x40,
	MSI_PSU_CMD_FAN_SETTING = 0x41,
	MSI_PSU_CMD_READ_FANDUTY = 0x42,
	MSI_PSU_CMD_WRITE = 0x50,
	MSI_PSU_CMD_READ = 0x51,
	MSI_PSU_CMD_MULTIRAIL_OCP = 0xC0,
	MSI_PSU_CMD_RUNTIME_NOW = 0xD0,
	MSI_PSU_CMD_RUNTIME_TOTAL = 0xD1,
	MSI_PSU_CMD_READ_ALL = 0xE0,
	MSI_PSU_CMD_READ_ALERTSTATUS = 0xE1,
	MSI_PSU_CMD_SAVE_SETTING = 0xF1,
	MSI_PSU_CMD_HANDSHAKE = 0xFA
};

#endif // MSI_PSU_H
